---

- name: copy tls files
  copy:
    src: "{{ item }}"
    dest: ""{{ odk_dir }}/docker/tomcat/tls/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items: "{{ odk_tls_files }}"

- name: render server.xml
  template:
    src: server.xml.j2
    dest: "{{ odk_dir }}/docker/tomcat/server.xml"

- name: ensure /tmp/ODKAggregate-settings dir exist
  file:
    path: "{{ odk_dir }}/docker/tomcat/ODKAggregate-settings"
    state: directory
    mode: 0755

- name: render odk settings
  template:
    src: "ODKAggregate-settings/{{ item }}.j2"
    dest: "{{ odk_dir }}/docker/tomcat/ODKAggregate-settings/{{ item }}"
  with_items: "{{ odk_settings_templates }}"
  notify: make ODKAggregate-settings.jar

