---

- name: copy odk_tls_key
  copy:
    src: "{{ odk_tls_key }}"
    dest: ""{{ odk_dir }}/docker/tomcat/tls/{{ odk_tls_key  }}"
    owner: root
    group: root
    mode: 0600

- name: copy odk_tls_cert
  copy:
    src: "{{ odk_tls_cert }}"
    dest: ""{{ odk_dir }}/docker/tomcat/tls/{{ odk_tls_cert  }}"
    owner: root
    group: root
    mode: 0600

- name: render server.xml
  template:
    src: server.xml.j2
    dest: "{{ odk_dir }}/docker/tomcat/server.xml"

- name: ensure /tmp/ODKAggregate-settings dir exist
  file:
    path: "{{ odk_dir }}/docker/tomcat/ODKAggregate-settings"
    state: directory
    mode: 0755

- name: render odk settings
  template:
    src: "ODKAggregate-settings/{{ item }}.j2"
    dest: "{{ odk_dir }}/docker/tomcat/ODKAggregate-settings/{{ item }}"
  with_items: "{{ odk_settings_templates }}"
  notify: make ODKAggregate-settings.jar

