---

- name: render server.xml
  template:
    src: server.xml.j2
    dest: /tmp/server.xml

- name: render odk settings
  template:
    src: "ODKAggregate-settings/{{ item }}.j2"
    dest: "/tmp/ODKAggregate-settings/{{ item }}"
  with_items: "{{ odk_settings_templates }}"
  notify: make ODKAggregate-settings.jar

