---

- name: Test Architecture
  assert:
    that:
      - "ansible_architecture == 'x86_64'"
    msg: "Architecture must be x86_64."

- name: Test Distribution
  assert:
    that:
      - "ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'"
    msg: "Distribution must be Ubuntu or Debian."

- name: Test Distribution Release
  assert:
    that:
      - "ansible_distribution_release == 'xenial' or ansible_distribution_release == 'trusty' or ansible_distribution_release == 'jessie'"
    msg: "Distribution must be Ubuntu Xenial, Trusty or Debian Jessie."

- name: install odk dependency packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ odk_dependency_packages }}"

- name: git clone odk-aggregate
  git:
    repo: https://github.com/Smartbrood/odk-aggregate.git
    dest: /usr/local/odk-aggregate

- name: copy systemd service files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ odk_systemd_files }}"
  notify: reload systemd

- meta: flush_handlers

- name: start mariadb
  systemd:
    name: mariadb-docker.service
    state: started
    enabled: True

- name: wait for mariadb to be available
  shell: "docker-compose exec mariadb /bin/sh -c 'echo "show databases;" > /sql.txt' && docker-compose exec mariadb /bin/sh -c 'mysql -uroot -p{{ mariadb_root_password }} < /sql.txt' || true"
  args:
    chdir: /usr/local/odk-aggregate
  register: result
  until: result.stderr.find("information_schema") != -1
  retries: 30
  delay: 5

- name: start tomcat
  systemd:
    name: tomcat-docker.service
    state: started
    enabled: True

- name: wait for tomcat port
  wait_for:
    port: 8080
    delay: 10


