---

- name: reload systemd
  command: systemctl daemon-reload

- name: make ODKAggregate-settings.jar
  command: "jar -cvf {{ odk_dir }}/docker/tomcat/ODKAggregate-settings.jar -C {{ odk_dir }}/docker/tomcat/ODKAggregate-settings ."
