---

odk_dir: /usr/local/odk-aggregate

odk_vhost: example.org
odk_tls_key: key.pem
odk_tls_cert: cert.pem

odk_superuser: aggregate
odk_realmstring: "odk ODK Aggregate"

odk_dependency_packages:
  - fastjar
  - make
  - git

odk_systemd_files:
  - mariadb-docker.service
  - tomcat-docker.service

odk_settings_templates:
  - jdbc.properties
  - logging.properties
  - odk-common-security-settings.xml
  - odk-security-settings.xml
  - odk-settings.xml
  - security.properties

mariadb_root_password: secret
