---

odk_dir: /usr/local/odk-aggregate

odk_vhost: example.org

odk_superuser: aggregate
odk_realmstring: "odk ODK Aggregate"

odk_dependency_packages:
  - fastjar
  - make
  - git

odk_tls_files:
  - key.pem
  - cert.pem

odk_systemd_files:
  - mariadb-docker.service
  - tomcat-docker.service

odk_settings_templates:
  - jdbc.properties
  - logging.properties
  - odk-common-security-settings.xml
  - odk-security-settings.xml
  - odk-settings.xml
  - security.properties

mariadb_root_password: secret
